### ISSUE TITLE
New Zwave Binding Request

### ISSUE THREAD

**Issue by bakerpj** [cdjackson/HABmin2#115] opened 2016-01-20 11:49 UTC
Can you please add the Somfy ZRTSI device to the Openhab database. The device is listed in the Pepper database. Here is the link to the XML file

http://www.pepper1.net/zwavedb/device/380/380-0047-5a52-5400-00-03-14-00-00.xml

Thanks.

**Comment by cdjackson** [comment] 2016-01-21 09:09
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by bakerpj** [comment] 2016-01-21 11:42
Chris,
I have created a logon account on the web site.
Email  bakerpjohn@yahoo.comUsername  bakerpj
Please provide me with the edit access so that I can update the device database.
Thank you. 

    On Thursday, January 21, 2016 12:09 PM, Chris Jackson <notifications@github.com> wrote:
 

 Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guideYou will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.—

**Comment by cdjackson** [comment] 2016-01-21 12:30
Done - thanks (any issue, just let me know).

**Comment by SigTill** [comment] 2016-01-26 19:51
Sorry if this is not correct way to use github - newbie. Trying to add Fibaro Wall PLug (FGWPF-102) and found this on the pepper-database: http://www.pepper1.net/zwavedb/device/517 . Can I also help to add this to your database? E-mail to logon: sherstad@gmail.com

**Comment by cdjackson** [comment] 2016-01-26 21:04
The wall plug should be in the database - you might have a version that is slightly different - can you provide the name that HABmin gives it (it should list the type/id numbers - we need this information for your device).

**Comment by SigTill** [comment] 2016-01-26 21:10
As I havent used habmin and openhab2 before I havent got it up and running yet. Not sure why. Trying to use the log:tail to look after errors and the start_debug.sh to get more information. I`m guessing that  my installation of openhab2 nightly and habmin2 is not correctly - will have to sort that out first.  Only have that one device yet so not 100% sure if the Rapsberry Pi 2, Aeon Labs USB stick (http://www.amazon.com/Aeon-Labs-DSA02203-ZWUS-Z-Wave-Z-Stick/dp/B003MWQ30E) or Fibaro Wall stick is the issue yet. Will see if I get that up and running for sure first.

**Comment by klee3d** [comment] 2016-03-15 04:59
Hi Chris,

Could I please get access to your online database editor?  I was going to ask if you could add the Cooper RF9517 Accessory Switch to the database, but perhaps I can help test doing it with your new editor.  
email kimleecg@gmail.com   username here is klee3d

**Comment by cdjackson** [comment] 2016-03-15 08:42
Hi,
No problem, but it doesn’t look like you’re registered… Please register on the website, and I’ll keep an eye out for your registration and will give you access to the database.

Thanks
Chris

**Comment by klee3d** [comment] 2016-03-15 11:16
Ah got it.  Ok

**Comment by cdjackson** [comment] 2016-03-15 13:06
I’ve updated your access…

**Comment by klee3d** [comment] 2016-03-15 15:17
Thanks Chris, will try adding a device this evening when i get home from
work.  perhaps even update the RF9501 you have in the list that is flagged
with more info required, as i have one of those as well.

On Tue, Mar 15, 2016 at 9:06 AM, Chris Jackson <notifications@github.com>
wrote:

> I’ve updated your access…
>
>
> > On 15 Mar 2016, at 11:16, klee3d <notifications@github.com> wrote:
> >
> > Ah got it. Ok
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141 <
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196807741
>



-- 
Kim Lee
Worlds Away Productions, Ltd.
www.worldsaway.tv
917-304-3010

**Comment by klee3d** [comment] 2016-03-16 01:00
Thanks Chris.
So I just made my first (and second) attempt to add this switch to the
database. I opened the xml file in a text editor on an imac and copy/pasted
to the xml field on your submission page.  both time it came up with the
following warning/alert:


   - Parameter 201 has minimum or maximum value as negative number.
   - Parameter 202 has minimum or maximum value as negative number.
   - Parameter 203 has minimum or maximum value as negative number.
   - Parameter 204 has minimum or maximum value as negative number.

and I was also wondering why at the bottom under DEVICE OVERVIEW it listed
the Aeon Labs Multisensor 6, which is definitely NOT the device I was
submitting.   Just for kicks I am pasting the xml into this email.  What am
i doing wrong? Or is this normal?  Thanks so much for all your efforts in
this field.

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>REMOTE_SWITCH</genericDeviceClass>
    <specificDeviceClass>SWITCH_REMOTE_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>0xddc4d5b3</homeId>
  <nodeId>15</nodeId>
  <version>4</version>
  <manufacturer>0x1a</manufacturer>
  <deviceId>0x0</deviceId>
  <deviceType>0x5352</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <security>false</security>
  <beaming>true</beaming>
  <maxBaudRate>40000</maxBaudRate>
  <nodeInformationFrame/>
  <supportedCommandClasses>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>INDICATOR</commandClass>
      <indicatorCommandClass>
        <version>1</version>
        <instances>1</instances>
        <indicator>255</indicator>
        <isGetSupported>true</isGetSupported>
      </indicatorCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>1</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_ALL</commandClass>
      <switchAllCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
        <mode>SWITCH_ALL_INCLUDE_ON_OFF</mode>
      </switchAllCommandClass>
    </entry>
    <entry>
      <commandClass>NODE_NAMING</commandClass>
      <nameLocationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <initialiseName>true</initialiseName>
        <initialiseLocation>true</initialiseLocation>
        <name>Remote Switch&#x0;&#x0;&#x0;</name>

<location>&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;</location>
      </nameLocationCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.52</protocolVersion>
        <applicationVersion>3.13</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SCENE_ACTIVATION</commandClass>
      <sceneActivationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </sceneActivationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>2</int>
    <int>7</int>
    <int>10</int>
  </nodeNeighbors>
  <lastSent>2016-03-16 00:40:37.642 UTC</lastSent>
  <lastReceived>2016-03-16 00:40:37.726 UTC</lastReceived>
</node>



On 3/15/16 9:06 AM, Chris Jackson wrote:

I’ve updated your access…


> On 15 Mar 2016, at 11:16, klee3d <notifications@github.com> wrote:
>
> Ah got it. Ok
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141 <
https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196807741



On Tue, Mar 15, 2016 at 9:06 AM, Chris Jackson <notifications@github.com>
wrote:

> I’ve updated your access…
>
>
> > On 15 Mar 2016, at 11:16, klee3d <notifications@github.com> wrote:
> >
> > Ah got it. Ok
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141 <
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196807741
>



-- 
Kim Lee
Worlds Away Productions, Ltd.
www.worldsaway.tv
917-304-3010

**Comment by klee3d** [comment] 2016-03-16 01:21
So I hope this doesn't screw anything up but I decided to try adding this
switch manually.  Entered all the initial info and then tried to update it
with the same xml copy paste data.  I received an ERROR PARSING XML FILE.

Not sure why as this XML was created by openHAB 1 so I would assume it is
formatted properly. I would really like to understand this process better
so I can be of more help.  Thanks for your patience.

Kim

On Tue, Mar 15, 2016 at 9:06 AM, Chris Jackson <notifications@github.com>
wrote:

> I’ve updated your access…
>
>
> > On 15 Mar 2016, at 11:16, klee3d <notifications@github.com> wrote:
> >
> > Ah got it. Ok
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141 <
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196769141>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/cdjackson/HABmin2/issues/115#issuecomment-196807741
>



-- 
Kim Lee
Worlds Away Productions, Ltd.
www.worldsaway.tv
917-304-3010

**Comment by cdjackson** [comment] 2016-03-16 12:53
Remove this line -:

><location>&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;&#x0;</location>

If you put this in any XML checker, you will likely find it's invalid as the & sign is not permitted in XML.

**Comment by klee3d** [comment] 2016-03-17 02:09
Hi Chris,
So i am checking these openHab 1 generated xml files with an online checker
and like you said there are illegal characters like this:
<name>Remote Switch&#x0;&#x0;&#x0;</name>
so 2 quick questions:
is that normal for openHAB to generate xml's with illegal characters or is
it user error?
I noticed that the xml files are all locked (using raspberry pi with
rasbian) and I am not exactly a linux pro.  should i try to
unlock/edit/resave them?
Thanks for your advice.


On Wed, Mar 16, 2016 at 8:53 AM, Chris Jackson <notifications@github.com>
wrote:

> Remove this line -:
>
> ����������������
>
> If you put this in any XML checker, you will likely find it's invalid as
> the & sign is not permitted in XML.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/cdjackson/HABmin2/issues/115#issuecomment-197308707>
>



-- 
Kim Lee
Worlds Away Productions, Ltd.
www.worldsaway.tv
917-304-3010

**Comment by cdjackson** [comment] 2016-03-17 11:44
Clearly it's not correct. I think it's solved in the OH2 binding now - it's caused by invalid characters in the node naming class...  I think (personally) this is a bug in the XStream library that writes the XML files since it shouldn't create invalid XML files!

You should just be able to open the file, remove the two lines that have these characters, and then paste it into the database...

**Comment by cdjackson** [comment] 2016-04-16 09:26
This issue seems to have changed direction from the original request. If the original request is not fulfilled, please reopen, but I'll otherwise close this.

**Closed by cdjackson** 2016-04-16 09:26 UTC
Labels: Database
