### ISSUE TITLE
Habmin not working with OH1

### ISSUE THREAD

**Issue by 5LICK** [cdjackson/HABmin2#91] opened 2015-10-05 18:15 UTC
Hello, I tried to use Habmin but I did not succeed. I did everything as written in the instructions but all time will be displayed in the browser console a lot of errors (errors with /rest/events?topics=smarthome/inbox/*). I tried different versions of add-ons

**Comment by cdjackson** [comment] 2015-10-05 21:37
What browser are you using?  If it's internet explorer then you might want to consider upgrading to a modern browser. If not please provide the error information.

**Comment by 5LICK** [comment] 2015-10-06 10:11
I use Mozilla Firefox, when i install Habmin, i see errors in browser dev console.
When i use this link http://cdjackson.github.io/HABmin2 - its ok.

My steps of installation Habmin:
1. I put habmin jar v 1.7.0 and zwave jar 1.7.0 in to /addons/ folder
2. I download last release Habmin files and put in webapps/habmin2 (https://github.com/cdjackson/HABmin2/releases)
3. I started openhab1 and used url http://127.0.0.1/habmin2 and i got errors with rest requests and angularjs errors.

What libraries should I use, there are different versions of Habmin -i found 1.5.0, 1.7.0?

**Comment by cdjackson** [comment] 2015-10-06 16:04
Please can you post the errors.  It’s probably normal since you’re using OH1, and the services that I think are giving you errors are only associated with OH2.

**Comment by cdjackson** [comment] 2015-10-07 20:18
I note that the title of this is that the software doesnt work with OH1. I think this is wrong - you are getting some errors, but these errors are just caused by the fact that it is running under OH1, and looking for services that arenot availble in OH2.

Can you confirm what actually doesn't work? Or at least provide the list of errors that you are seeing? If the errors are just about the events as you state above, then this is perfectly normal as the event service is not used in OH1.

**Comment by 5LICK** [comment] 2015-10-07 23:48
I use now addons - `habmin jar v.1.7.0` and `zwave jar v1.8.0`
Started logs:
```
2015-10-08 02:26:19.973 [INFO ] [.o.io.habmin.HABminApplication] - Started HABmin REST API at /services/habmin
2015-10-08 02:26:31.167 [INFO ] [.service.AbstractActiveService] - NTP Refresh Service has been started
2015-10-08 02:26:31.211 [INFO ] [.z.internal.ZWaveActiveBinding] - ZWave 'updated' with null config
```

and open link 127.0.0.1:8080/habmin2 (i see my sitemap, but it link not work - empty page)
![main](https://cloud.githubusercontent.com/assets/1235424/10354082/3f78708c-6d65-11e5-905e-8c117c90c204.PNG)

I have this errors and warnings in console:
![errors](https://cloud.githubusercontent.com/assets/1235424/10354084/3f7a4eac-6d65-11e5-921a-eae9ff3efaef.PNG)

and information of request (rest/events)
![rest](https://cloud.githubusercontent.com/assets/1235424/10354083/3f7919f6-6d65-11e5-80d2-1359ce380733.PNG)

I runned OH1 with debug mode:
```
02:40:21.206 [DEBUG] [io.rest.internal.RESTActivator:33   ] - REST API has been started.
02:40:21.296 [INFO ] [org.atmosphere.util.IOUtils   :370  ] - META-INF/services/org.atmosphere.cpr.AtmosphereFramework not found in class loader
02:40:21.326 [INFO ] [sphere.cpr.AtmosphereFramework:2601 ] - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation

02:40:21.206 [DEBUG] [io.rest.internal.RESTActivator:33   ] - REST API has been started.
02:40:21.296 [INFO ] [org.atmosphere.util.IOUtils   :370  ] - META-INF/services/org.atmosphere.cpr.AtmosphereFramework not found in class loader
02:40:21.326 [INFO ] [sphere.cpr.AtmosphereFramework:2601 ] - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
02:40:21.326 [INFO ] [cpr.DefaultAnnotationProcessor:138  ] - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
02:40:21.346 [WARN ] [cpr.DefaultAnnotationProcessor:178  ] - Unable to detect annotations. Application may fail to deploy.
02:40:21.373 [INFO ] [sphere.cpr.AtmosphereFramework:1891 ] - Auto detecting atmosphere handlers /WEB-INF/classes/
02:40:21.388 [INFO ] [sphere.cpr.AtmosphereFramework:639  ] - Installed AtmosphereHandler org.atmosphere.handler.ReflectorServletProcessor mapped to context-path /* and Broadcaster Class org.atmosphere.jersey.JerseyBroadcaster
02:40:21.388 [INFO ] [sphere.cpr.AtmosphereFramework:1945 ] - Auto detecting WebSocketHandler in /WEB-INF/classes/
02:40:21.388 [INFO ] [sphere.cpr.AtmosphereFramework:1602 ] - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
02:40:21.438 [INFO ] [.a.h.ReflectorServletProcessor:103  ] - Installing Servlet com.sun.jersey.spi.container.servlet.ServletContainer
02:40:21.548 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:815  ] - Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM'
02:40:21.548 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:826  ] - Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
02:40:21.608 [INFO ] [j.s.i.a.DeferredResourceConfig:101  ] - Instantiated the Application class org.openhab.io.rest.RESTApplication
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2435 ] - AtmosphereInterceptor CORS Interceptor Support will always be executed first
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT 
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT 
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT 
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
02:40:22.408 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT 
02:40:22.418 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT 
02:40:22.418 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT 
02:40:22.418 [INFO ] [sphere.cpr.AtmosphereFramework:935  ] - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
02:40:22.418 [WARN ] [sphere.cpr.AtmosphereFramework:941  ] - No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
02:40:22.418 [INFO ] [sphere.cpr.AtmosphereFramework:949  ] - Default Broadcaster Class: org.atmosphere.jersey.JerseyBroadcaster
02:40:22.428 [INFO ] [sphere.cpr.AtmosphereFramework:950  ] - Broadcaster Polling Wait Time 100
02:40:22.428 [INFO ] [sphere.cpr.AtmosphereFramework:951  ] - Shared ExecutorService supported: true
02:40:22.428 [INFO ] [sphere.cpr.AtmosphereFramework:958  ] - Messaging Thread Pool Size: 10
02:40:22.428 [INFO ] [sphere.cpr.AtmosphereFramework:968  ] - Async I/O Thread Pool Size: 10
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:979  ] - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:980  ] - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:990  ] - Invoke AtmosphereInterceptor on WebSocket message true
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:991  ] - HttpSession supported: false
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:993  ] - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
02:40:22.438 [INFO ] [sphere.cpr.AtmosphereFramework:994  ] - Atmosphere is using async support: org.atmosphere.container.JettyAsyncSupportWithWebSocket running under container: jetty/8.1.3.v20120522 with WebSocket enabled.
02:40:22.448 [INFO ] [sphere.cpr.AtmosphereFramework:996  ] - Atmosphere Framework 2.2.5 started.
02:40:22.448 [INFO ] [sphere.cpr.AtmosphereFramework:998  ] - 

	For Atmosphere Framework Commercial Support, visit 
	http://www.async-io.org/ or send an email to support@async-io.org

02:40:22.448 [INFO ] [penhab.io.rest.RESTApplication:144  ] - Started REST API at /rest
02:40:22.448 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server._tcp.local. at port 8080
02:40:23.048 [INFO ] [sphere.cpr.AtmosphereFramework:1053 ] - Latest version of Atmosphere's JavaScript Client 2.2.12
02:40:23.048 [INFO ] [sphere.cpr.AtmosphereFramework:1060 ] - 

	Atmosphere Framework Updates:
	Minor Update available (bugs fixes): 2.2.8
02:40:27.858 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server-ssl._tcp.local. at port 8443

java.lang.ClassNotFoundException: org.atmosphere.interceptor.DefaultHeadersInterceptor
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	
02:40:49.834 [DEBUG] [nhab.io.habmin.HABminActivator:33   ] - HABmin Interface has been started.
02:40:49.854 [INFO ] [org.atmosphere.util.IOUtils   :370  ] - META-INF/services/org.atmosphere.cpr.AtmosphereFramework not found in class loader
02:40:49.864 [INFO ] [sphere.cpr.AtmosphereFramework:2601 ] - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
02:40:49.864 [INFO ] [cpr.DefaultAnnotationProcessor:138  ] - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
02:40:49.874 [WARN ] [cpr.DefaultAnnotationProcessor:178  ] - Unable to detect annotations. Application may fail to deploy.
02:40:49.894 [INFO ] [sphere.cpr.AtmosphereFramework:1891 ] - Auto detecting atmosphere handlers /WEB-INF/classes/
02:40:49.914 [INFO ] [sphere.cpr.AtmosphereFramework:639  ] - Installed AtmosphereHandler org.atmosphere.handler.ReflectorServletProcessor mapped to context-path /* and Broadcaster Class org.atmosphere.jersey.JerseyBroadcaster
02:40:49.914 [INFO ] [sphere.cpr.AtmosphereFramework:1945 ] - Auto detecting WebSocketHandler in /WEB-INF/classes/
02:40:49.924 [INFO ] [sphere.cpr.AtmosphereFramework:1602 ] - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
02:40:49.924 [INFO ] [.a.h.ReflectorServletProcessor:103  ] - Installing Servlet com.sun.jersey.spi.container.servlet.ServletContainer
02:40:49.934 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:815  ] - Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM'
02:40:49.934 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:826  ] - Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
02:40:49.964 [INFO ] [j.s.i.a.DeferredResourceConfig:101  ] - Instantiated the Application class org.openhab.io.habmin.HABminApplication
02:40:50.444 [WARN ] [sphere.cpr.AtmosphereFramework:1097 ] - 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT 
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:935  ] - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
02:40:50.444 [WARN ] [sphere.cpr.AtmosphereFramework:941  ] - No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
02:40:50.444 [INFO ] [sphere.cpr.AtmosphereFramework:949  ] - Default Broadcaster Class: org.atmosphere.jersey.JerseyBroadcaster
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:950  ] - Broadcaster Polling Wait Time 100
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:951  ] - Shared ExecutorService supported: true
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:958  ] - Messaging Thread Pool Size: Unlimited
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:968  ] - Async I/O Thread Pool Size: 200
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:979  ] - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:980  ] - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:990  ] - Invoke AtmosphereInterceptor on WebSocket message true
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:991  ] - HttpSession supported: false
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:993  ] - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:994  ] - Atmosphere is using async support: org.atmosphere.container.JettyAsyncSupportWithWebSocket running under container: jetty/8.1.3.v20120522 with WebSocket enabled.
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:996  ] - Atmosphere Framework 2.2.5 started.
02:40:50.454 [INFO ] [sphere.cpr.AtmosphereFramework:998  ] - 

	For Atmosphere Framework Commercial Support, visit 
	http://www.async-io.org/ or send an email to support@async-io.org

02:40:50.454 [INFO ] [.o.io.habmin.HABminApplication:182  ] - Started HABmin REST API at /services/habmin
02:40:50.454 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server._tcp.local. at port 8080
02:40:50.754 [INFO ] [sphere.cpr.AtmosphereFramework:1053 ] - Latest version of Atmosphere's JavaScript Client 2.2.12
02:40:50.764 [INFO ] [sphere.cpr.AtmosphereFramework:1060 ] - 

	Atmosphere Framework Updates:
	Minor Update available (bugs fixes): 2.2.8
02:40:53.154 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server-ssl._tcp.local. at port 8443

02:41:18.438 [DEBUG] [p.r.i.charts.RRD4jChartServlet:118  ] - Starting up rrd chart servlet at /rrdchart.png
02:41:18.588 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from ptbtime1.ptb.de: 8 ??????? 2015 ?. 2:41:18 EEST
02:41:26.432 [DEBUG] [.r.i.resources.SitemapResource:107  ] - Received HTTP GET request at 'sitemaps' for media type 'null'.
02:41:26.442 [DEBUG] [.r.i.resources.SitemapResource:228  ] - Received HTTP GET request at 'http://127.0.0.1:8080/rest/sitemaps'.
```

**Comment by ddoll** [comment] 2015-10-08 06:23
I don't think that the ClassNotFoundException is thrown by Habmin. 
Did you see the same exception of you start without Habmin?

**Comment by 5LICK** [comment] 2015-10-08 09:54
It is? `java.lang.ClassNotFoundException: org.atmosphere.interceptor.DefaultHeadersInterceptor`
Full list this:
```
java.lang.ClassNotFoundException: org.atmosphere.interceptor.DefaultHeadersInterceptor
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107) ~[org.eclipse.osgi_3.8.2.v20130124-134944.jar:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_60]
	at org.atmosphere.util.IOUtils.loadClass(IOUtils.java:309) ~[atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.atmosphere.cpr.AtmosphereFramework.configureAtmosphereInterceptor(AtmosphereFramework.java:1094) [atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:892) [atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:780) [atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.atmosphere.cpr.AtmosphereServlet.configureFramework(AtmosphereServlet.java:101) [atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.atmosphere.cpr.AtmosphereServlet.init(AtmosphereServlet.java:80) [atmosphere-runtime-2.2.5.jar:2.2.5]
	at org.eclipse.equinox.http.servlet.internal.ServletRegistration.init(ServletRegistration.java:49) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.registerServlet(ProxyServlet.java:179) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.eclipse.equinox.http.servlet.internal.HttpServiceImpl.registerServlet(HttpServiceImpl.java:66) [org.eclipse.equinox.http.servlet_1.1.300.v20120522-1841.jar:na]
	at org.openhab.io.habmin.HABminApplication.activate(HABminApplication.java:179) [bundlefile:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_60]
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.1.v20120926-201320.jar:na]
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.400.v20120917-192807.jar:na]
```
WIthout habmin i not see this errors? It is a problem with `Atmosphere`?

**Comment by cdjackson** [comment] 2015-10-08 17:33
I would suggest to close this since it isn’t a problem with HABmin2 - it’s obviously HABmin1.

The problem might be an issue with Atmosphere since it has been updated, but in any case, it’s an HABmin1 problem and nothing to do with HABmin2

**Comment by 5LICK** [comment] 2015-10-08 17:38
Well, the problem with OH1 and with Atmosphere. 
I need to use OH2?

Close.

**Comment by cdjackson** [comment] 2015-10-08 17:58
I’m not sure what you mean? This project is for HABmin2, which include the OH2 JAR, and the associated web files. The issue that you see is an error in HABmin1, or possibly the latest Atmosphere being incompatible with HABmin. The issue doesn’t belong here, so if you want it looked at it’s worth raising an issue on HABmin 1.

**Comment by 5LICK** [comment] 2015-10-08 18:09
```This project is for HABmin2, which include the OH2 JAR```
Sorry, i cant find them, in release zip i see only web files

**Closed** 2015-10-08 18:12 UTC
Labels: Question

**Comment by cdjackson** [comment] 2015-10-08 18:14
There are no Java files in from this repository that are applicable to OH1 - this is the point. Since the problem is within Java, it is not part of OH2 I think?
