### ISSUE TITLE
Error writing habmin rule file

### ISSUE THREAD

**Issue by hfanieng** [cdjackson/HABmin2#141] opened 2016-03-19 22:23 UTC
Trying to create a rule and saving it with this interesting feature in HABmin results in an error inside the log:

```
23:18:24.514 [ERROR] [.designer.blocks.DesignerRuleCreator] - Error writing habmin rule file :
java.io.FileNotFoundException: conf/rules/(1)_hue_schaltet_arbeitsbereich_aus.rules (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)[:1.8.0_72]
	at java.io.FileOutputStream.open(FileOutputStream.java:270)[:1.8.0_72]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)[:1.8.0_72]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)[:1.8.0_72]
	at org.openhab.ui.habmin.internal.services.designer.blocks.DesignerRuleCreator.saveRule(DesignerRuleCreator.java:249)
	at org.openhab.ui.habmin.internal.services.designer.DesignerResource.putDesignBean(DesignerResource.java:268)
	at org.openhab.ui.habmin.internal.services.designer.DesignerResource.putDesignRef(DesignerResource.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_72]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)[12:com.eclipsesource.jaxrs.jersey-min:2.22.1]
	at com.eclipsesource.jaxrs.publisher.internal.ServletContainerBridge.service(ServletContainerBridge.java:76)[14:com.eclipsesource.jaxrs.publisher:5.3.0.201512270850]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)[73:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[73:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[137:org.ops4j.pax.web.pax-web-jetty:4.2.3]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[71:org.eclipse.jetty.security:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)[137:org.ops4j.pax.web.pax-web-jetty:4.2.3]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[73:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[137:org.ops4j.pax.web.pax-web-jetty:4.2.3]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.Server.handle(Server.java:497)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[72:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[64:org.eclipse.jetty.io:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[75:org.eclipse.jetty.util:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[75:org.eclipse.jetty.util:9.2.10.v20150310]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_72]
```

**Comment by cdjackson** [comment] 2016-03-23 10:42
This is probably caused by hard coded (OH1) folder structure which should be easy to resolve...

**Comment by cdjackson** [comment] 2016-03-26 16:10
This should be fixed in the next update (tonight probably)

**Closed** 2016-05-27 23:12 UTC
Labels: Awaiting Feedback, Bug, Complete: Close at next release
